name: Hexademic Consciousness Engine CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Unreal Engine base image
        run: docker pull ghcr.io/epicgames/unreal-engine:5.3.2-windows

      - name: Build Hexademic Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/hexademic-consciousness-engine:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/hexademic-consciousness-engine:latest
