name: 'Repo Lockdown'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
  schedule:
    - cron: '0 * * * *'  # Every hour

permissions:
  issues: write
  pull-requests: write

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - name: Lock issues and PRs
        uses: dessant/repo-lockdown@v2
        with:
          issue-comment: >
            🚫 Epic Games does not accept issues on this repository.
            Please visit [Unreal Engine Support](https://www.unrealengine.com/support) for assistance.
          pr-comment: >
            🚫 Epic Games does not accept pull requests on this repository.
            Please visit [Unreal Engine Support](https://www.unrealengine.com/support) for assistance.
