name: Unreal Engine C++ CI

on:
  push:
    branches: [ "Source" ]
  pull_request:
    branches: [ "Source" ]

jobs:
  build:
    container: ghcr.io/epicgames/unreal-engine:5.3.2-windows # Replace with an accessible image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Unreal Project/Plugin
      run: |
        UE_ROOT="/home/ue4/UnrealEngine"  # Adjust path based on the new image's docs
        cd ${{ github.workspace }}
        chmod +x "${UE_ROOT}/Engine/Build/BatchFiles/RunUAT.sh"
        "${UE_ROOT}/Engine/Build/BatchFiles/RunUAT.sh" BuildCookRun \
        -project="${{ github.workspace }}/YourProjectName.uproject" \
        -noP4 \
        -platform=Linux \
        -clientconfig=Development \
        -build \
        -plugin="HexademicPlugin" \
        -skipcook \
        -pak \
        -nocompileeditor \
        -stage \
        -stagingdirectory="${{ github.workspace }}/StagingBuild" \
        -utf8output |
        # Adjust this path based on the Docker image's UE installation location.
        UE_ROOT="/home/ue4/UnrealEngine" # Common path in some UE Docker images

        # Navigate to your project root within the container's workspace
        cd ${{ github.workspace }}

        # Ensure RunUAT.sh is executable (it usually is in UE Docker images, but good for safety)
        chmod +x "${UE_ROOT}/Engine/Build/BatchFiles/RunUAT.sh"

        "${UE_ROOT}/Engine/Build/BatchFiles/RunUAT.sh" BuildCookRun \
        -project="${{ github.workspace }}/YourProjectName.uproject" \
        -noP4 \
        -platform=Linux \
        -clientconfig=Development \
        -build \
        -plugin="HexademicPlugin" \
        -skipcook \
        -pak \
        -nocompileeditor \
        -stage \
        -stagingdirectory="${{ github.workspace }}/StagingBuild" \
        -utf8output
