name: Unreal Engine 5.3.2 Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOCKER_USER: ${{ secrets.GHCR_USER || github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo $env:DOCKER_PASSWORD | docker login ghcr.io -u $env:DOCKER_USER --password-stdin
        shell: pwsh

      - name: Pull Unreal Engine Docker Image
        run: |
          docker pull ghcr.io/epicgames/unreal-engine:5.3.2-windows
        shell: pwsh

      # Optional: Run your build inside the container
      # - name: Build in Unreal Container
      #   run: |
      #     docker run --rm -v "${{ github.workspace }}:/workspace" ghcr.io/epicgames/unreal-engine:5.3.2-windows BuildCommandHere

    # Add your additional build, test, or artifact steps here
